= Cluster extensions
:idprefix:
:idseparator: -
:sectlinks:
:toc: auto

:uri-tag-policies: https://docs.oracle.com/en-us/iaas/Content/Tagging/Tasks/managingaccesswithtags.htm
:uri-ca-github: https://github.com/kubernetes/autoscaler/tree/master/charts/cluster-autoscaler
:uri-ca-oracle: https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengautoscalingclusters.htm
:uri-gatekeeper: https://open-policy-agent.github.io/gatekeeper

WARNING: The following options are provided as a reference for evaluation only, and may install software to the cluster that is not supported by or sourced from Oracle. These features should be enabled with caution as their operation is not guaranteed!

== Calico

NOTE: Documentation pending

== Cluster autoscaler
Deployed using the {uri-ca-github}[cluster-autoscaler Helm chart] with configuration from `worker_pools`.

The following parameters may be added on each pool definition to enable management or scheduling of the cluster autoscaler:

* `allow_autoscaler`: Enable scheduling of the cluster autoscaler deployment on a pool by adding a node label matching the deployment's nodeSelector, and an OCI tag for use with {uri-tag-policies}[IAM tag-based policies] granting access to the instances.
* `autoscale`: Enable cluster autoscaler management of the pool by including a `--nodes` argument for it.
* `minSize`: Define the minimum scale of a pool managed by the cluster autoscaler. Defaults to `size` when not provided.
* `maxSize`: Define the minimum scale of a pool managed by the cluster autoscaler. Defaults to `size` when not provided.

== Metrics server

NOTE: Documentation pending

== Prometheus

NOTE: Documentation pending
