= Instructions

:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:uri-repo: https://github.com/oracle-terraform-modules/terraform-oci-oke

:uri-rel-file-base: link:{uri-repo}/blob/v12docs
:uri-rel-tree-base: link:{uri-repo}/tree/v12docs

:uri-docs: {uri-rel-file-base}/docs

:uri-topology: {uri-docs}/topology.adoc
:uri-changelog: {uri-rel-file-base}/CHANGELOG.adoc
:uri-contribute: {uri-rel-file-base}/CONTRIBUTING.adoc
:uri-contributors: {uri-rel-file-base}/CONTRIBUTORS.adoc

:uri-configuration: {uri-docs}/configuration.adoc
:uri-license: {uri-rel-file-base}/LICENSE.txt
:uri-kubernetes: https://kubernetes.io/
:uri-networks-subnets-cidr: https://erikberg.com/notes/networks.html
:uri-oci: https://cloud.oracle.com/cloud-infrastructure
:uri-oci-documentation: https://docs.cloud.oracle.com/iaas/Content/home.htm
:uri-oke: https://docs.cloud.oracle.com/iaas/Content/ContEng/Concepts/contengoverview.htm
:uri-oracle: https://www.oracle.com
:uri-prereqs: {uri-docs}/prerequisites.adoc
:uri-quickstart: {uri-docs}/quickstart.adoc

:uri-terraform: https://www.terraform.io
:uri-terraform-cidrsubnet-desconstructed: http://blog.itsjustcode.net/blog/2017/11/18/terraform-cidrsubnet-deconstructed/
:uri-terraform-oci: https://www.terraform.io/docs/providers/oci/index.html
:uri-terraform-oke-sample: https://github.com/terraform-providers/terraform-provider-oci/tree/master/examples/container_engine
:uri-terraform-options: {uri-docs}/terraformoptions.adoc
:uri-install-kubectl: https://kubernetes.io/docs/tasks/tools/install-kubectl/
:uri-helm: https://helm.sh/
:uri-metricserver: https://kubernetes.io/docs/tasks/debug-application-cluster/resource-metrics-pipeline/#metrics-server
:uri-k8s-dashboard: http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

== Assumptions

This section assumes you have completed the following:

. all the {uri-prereqs}[pre-requisites]
. all the required {uri-configuration}[configuration]

=== Creating the OKE Cluster

Run the below command to initialize a working directory containing Terraform configuration files

----
terraform init
----
Then you can run the plan and apply commands to create OKE cluster and other components.
----
terraform plan
----
----
terraform apply
----

You can create the latest version of kubernetes available in OKE using this terraform script.By default the kubernetes_version parameter in terraform.tfvars.example is set as "LATEST". Refer {uri-terraform-options}#oke[kubernetes parameter] for other available parameters for OKE.

Use the parameter *cluster_name* to change the name as per your needs.


=== Adding the bastion host

If you want to use bastion host set the parameter *create_bastion = true* in terraform.tfvars.Please refer {uri-terraform-options}#bastion-host[Bastion parameters] for other available parameters.

=== Using the bastion host

****
*Assumption that create_bastion parameter is set to true in terraform.tfvars*
****

Once the terraform apply is successful you will get the bastion_public_ip as output and also a ssh command .You can also run the below command to get the output
----
terraform output
----

=== Interacting with the OKE Cluster locally

Kubectl installed in bastion host by default. If you would like to use kubectl locally in your windows or mac host .please refer {uri-install-kubectl}[Kubectl Install]. Set the KUBE_CONFIG to the config file path. kubeconfig file will get generated locally under the folder *generated* .

****
*Please install kubectl version same as OKE version for compatibility.*
****

=== Creating an auth token for OCIR

Oracle cloud infrastructure registry is a highly available private container registry service for storing and sharing container images within the same regions as the deployments.To pull images from OCIR please set the parameter *create_auth_token = true* in terraform.tfvars. Please refer {uri-terraform-options}#ocir[OCIR parameters] for other parameters to be set.

=== Installing helm

{uri-helm}[Helm] is a package manager for kubernetes.If you want to install helm .Set the parameter *install_helm = true* in terraform.tfvars. By default its set to true. An alias "*h*" will be created for helm. For other available parameters please refer {uri-terraform-options}#helm[Helm parameters].

=== Installing calico 

Calico enables networking and network policy in Kubernetes clusters across the cloud.To install calico set the parameter *install_calico = true* in terraform.tfvars.By default its set to false. Please refer {uri-terraform-options}#calico[Calico parameters] for other available parameters.

== Installing Metrics Server

{uri-metricserver}[Metricserver] can be installed by setting the parameter *install_metricserver = true* in terraform.tfvars.By default the latest version is installed in kube-system namespace.

=== Scaling the number of worker nodes

Set the parameter *node_pool_quantity_per_subnet* to the desired quantity.For single AD region a minimum quantity of 2 will get created .This is helpful to utilize the faultdomains for single AD region .Please refer {uri-topology}#fault-domains[Faultdomain]

=== Scaling the number of node pools

Set the parameter *node_pools* to the desired quantity. Please refer {uri-topology}#node-pools[Nodepool]

=== Accessing the Kubernetes dashboard

In a terminal window, run the command
----
kubectl proxy
----
Open a browser and go to {uri-k8s-dashboard}[Kubernetes Dashboard] to display the Kubernetes Dashboard.

=== Destroying the cluster

Run the below command to destroy the infrastructure created by terraform .
----
terraform destroy
----

****
*Only infrastructure created by terraform will get destroyed.*
****