= Quickstart

:idprefix:
:idseparator: -
:sectlinks:


:uri-repo: https://github.com/oracle-terraform-modules/terraform-oci-oke
:uri-rel-file-base: link:{uri-repo}/blob/master
:uri-rel-tree-base: link:{uri-repo}/tree/master
:uri-docs: {uri-rel-file-base}/docs
:uri-instructions: {uri-docs}/instructions.adoc
:uri-oci-keys: https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm
:uri-oci-ocids: https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm#five
:uri-oci-okepolicy: https://docs.cloud.oracle.com/iaas/Content/ContEng/Concepts/contengpolicyconfig.htm#PolicyPrerequisitesService
:uri-terraform: https://www.terraform.io
:uri-terraform-oci: https://www.terraform.io/docs/providers/oci/index.html
:uri-terraform-options: {uri-docs}/terraformoptions.adoc

. link:#assumptions[Assumptions]
. link:#pre-requisites[Pre-requisites]
. link:#instructions[Instructions]
. link:#related-documentation[Related documentation]

=== Assumptions

1. You have setup the {uri-oci-keys}[required keys]
2. You know the {uri-oci-ocids}[required OCIDs]
3. You have set the {uri-oci-okepolicy}[necessary OKE policy]

=== Pre-requisites

1. git is installed
2. ssh client is installed
3. Terraform 0.12.4+ is installed

=== Instructions for provisioning

1. Clone the repo:

[source,bash]
----
git clone https://github.com/oracle-terraform-modules/terraform-oci-oke.git tfoke

cd tfoke
cp terraform.tfvars.example terraform.tfvars
----

2. Set mandatory parameters:

* api_fingerprint
* api_private_key_path
* compartment_id
* compartment_name
* tenancy_id
* user_id

3. Override other parameters:

* region

4. Optional parameters to override:
* ssh_private_key_path
* ssh_public_key_path
* vcn_dns_label
* vcn_name
* bastion_enabled
* cluster_name
* worker_mode

5. Create a provider.tf file and add the following:

----
provider "oci" {
  tenancy_ocid         = var.tenancy_id
  user_ocid            = var.user_id
  fingerprint          = var.api_fingerprint
  private_key_path     = var.api_private_key_path
  region               = var.region
  disable_auto_retries = var.disable_auto_retries
}
----

=== Instructions for using as module
1. See basic example below:
```hcl
ariable "tenancy_id" {}
variable "user_id" {}
variable "api_fingerprint" {}
variable "api_private_key_path" {}
variable "region" {}
variable "disable_auto_retries" {}
variable "username" {}
variable "bastion_notification_endpoint" {}
variable "ssh_public_key_path" {}
variable "service_account_cluster_role_binding" {}
variable "compartment_id" {}
variable "cluster_name" {}
variable "bastion_timezone" {}
variable "email_address" {}
variable "existing_key_id" {}
variable "tenancy_name" {}
variable "vcn_name" {}
variable "node_pools" {}
variable "admin_notification_endpoint" {}
variable "vcn_dns_label" {}
variable "bastion_shape" {}
variable "ssh_private_key_path" {}
variable "label_prefix" {}
variable "admin_timezone" {}
module "terraform-oci-oke" {
  source                                = "../terraform-oci-oke"
  tenancy_name                          =   var.tenancy_name
  tenancy_id                            =   var.tenancy_id
  compartment_id                        =   var.compartment_id
  user_id                               =   var.user_id
  api_fingerprint                       =   var.api_fingerprint
  api_private_key_path                  =   var.api_private_key_path
  region                                =   var.region
  disable_auto_retries                  =   var.disable_auto_retries
  node_pools                            =   var.node_pools
  username                              =   var.username
  ssh_public_key_path                   =   var.ssh_public_key_path
  ssh_private_key_path                  =   var.ssh_private_key_path
  service_account_cluster_role_binding  =   var.service_account_cluster_role_binding
  cluster_name                          =   var.cluster_name
  email_address                         =   var.email_address
  existing_key_id                       =   var.existing_key_id
  vcn_name                              =   var.vcn_name
  admin_notification_endpoint           =   var.admin_notification_endpoint
  vcn_dns_label                         =   var.vcn_dns_label
  bastion_shape                         =   var.bastion_shape
  admin_timezone                        =   var.admin_timezone
  bastion_notification_endpoint         =   var.bastion_notification_endpoint
  bastion_timezone                      =   var.bastion_timezone
  label_prefix                          =   var.label_prefix
}
```

=== Related documentation:

* {uri-instructions}[Detailed Instructions]

* {uri-terraform-options}[All Terraform configuration options] for {uri-repo}[this project]
