= Quickstart

:idprefix:
:idseparator: -
:sectlinks:


:uri-repo: https://github.com/oracle-terraform-modules/terraform-oci-oke
:uri-rel-file-base: link:{uri-repo}/blob/main
:uri-rel-tree-base: link:{uri-repo}/tree/main
:uri-docs: {uri-rel-file-base}/docs
:uri-instructions: {uri-docs}/instructions.adoc
:uri-oci-keys: https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm
:uri-oci-ocids: https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm#five
:uri-oci-okepolicy: https://docs.cloud.oracle.com/iaas/Content/ContEng/Concepts/contengpolicyconfig.htm#PolicyPrerequisitesService
:uri-oci-provider: https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformproviderconfiguration.htm
:uri-terraform: https://www.terraform.io
:uri-terraform-oci: https://www.terraform.io/docs/providers/oci/index.html
:uri-terraform-options: {uri-docs}/terraformoptions.adoc
:uri-topology: {uri-docs}/topology.adoc
:uri-variables: {uri-rel-file-base}/variables.tf

. link:#assumptions[Assumptions]
. link:#pre-requisites[Pre-requisites]
. link:#instructions[Instructions]
. link:#related-documentation[Related documentation]

=== Assumptions

1. You have setup the {uri-oci-keys}[required keys]
2. You know the {uri-oci-ocids}[required OCIDs]
3. You have set the {uri-oci-okepolicy}[necessary OKE policy]

=== Pre-requisites

1. git is installed
2. ssh client is installed
3. Terraform 1.0.0+ is installed

=== Provisioning using this git repo

. Clone the repo:

+
[source,bash]
----
git clone https://github.com/oracle-terraform-modules/terraform-oci-oke.git tfoke

cd tfoke
cp terraform.tfvars.example terraform.tfvars
----

. Create a provider.tf file add 2 providers ({uri-oci-provider}[see different examples of creating providers]):
.. 1 provider for the region where your OKE cluster and other resources will be created
.. 1 provider for the home region. This is required for conducting identity operations. *Note that your home region may not necessarily be the same as your current region.*

+
----
provider "oci" {
  fingerprint      = "aa:bb:cc:dd:11"
  private_key_path = "/path/to/oci_rsa.pem"
  region           = "ap-sydney-1"
  tenancy_ocid     = "ocid1.tenancy...."
  user_ocid        = "ocid1.user.oc1.."
}

provider "oci" {
  fingerprint      = "aa:bb:cc:dd:11"
  private_key_path = "/path/to/oci_rsa.pem"
  region           = "us-phoenix-1"
  tenancy_ocid     = "ocid1.tenancy...."
  user_ocid        = "ocid1.user.oc1.."
  alias            = "home"
}
----

. Set mandatory parameters in the provider depending on your method of initializing your provider:

* api_fingerprint
* api_private_key_path
* compartment_id
* tenancy_id
* user_id

. Override other parameters e.g.:

* region (where your resources will be created)

. Run Terraform:

+
[source,bash]
----
terraform init
terraform plan
terraform apply
----

=== Provisioning using the HashiCorp registry module

. In your project root, create a provider.tf file and add the following:

+
----
provider "oci" {
  fingerprint          = var.api_fingerprint
  private_key_path     = var.api_private_key_path
  region               = var.region
  tenancy_ocid         = var.tenancy_id
  user_ocid            = var.user_id
}

provider "oci" {
  fingerprint          = var.api_fingerprint
  private_key_path     = var.api_private_key_path
  region               = "us-phoenix-1"
  tenancy_ocid         = var.tenancy_id
  user_ocid            = var.user_id
  alias                = "home"
}
----

. In your project root, create a variables.tf file and add variables for your project. You can copy the existing {uri-variables}[variables.tf] in the oke module root.

. In your project root, create a main.tf file and add the following:

+
----
module "oke" {
  source  = "oracle-terraform-modules/oke/oci"
  version = "4.0.0"
  # insert the 9 required variables here
}
----

. Edit your oke module definition and pass the required variables:

+
----
module "oke" {
  source                                =   "oracle-terraform-modules/oke/oci"
  version                               =   "4.0.0"

  compartment_id                        =   var.compartment_id
  tenancy_id                            =   var.tenancy_id
  user_id                               =   var.user_id

  ssh_private_key_path                  =   var.ssh_private_key_path
  ssh_public_key_path                   =   var.ssh_public_key_path

OR 

  ssh_private_key                       =   var.ssh_private_key
  ssh_public_key                        =   var.ssh_public_key

  label_prefix                          =   var.label_prefix
  region                                =   var.region

  vcn_dns_label                         =   var.vcn_dns_label
  vcn_name                              =   var.vcn_name

  create_bastion_host                   =   var.create_bastion_host
 
  create_operator                       =   var.create_operator

  # add additional parameters for availability_domains, oke etc as you need

}
----

. Run Terraform:

+
[source,bash]
----
terraform init
terraform plan
terraform apply
----

=== Related documentation:

* {uri-instructions}[Detailed Instructions]

* {uri-terraform-options}[All Terraform configuration options] for {uri-repo}[this project]
