= Quickstart
:idprefix:
:idseparator: -
:sectlinks:
:sectnums:
:toc: auto

:uri-repo: https://github.com/oracle-terraform-modules/terraform-oci-oke
:uri-rel-file-base: link:{uri-repo}/blob/main
:uri-rel-tree-base: link:{uri-repo}/tree/main
:uri-docs: {uri-rel-file-base}/docs
:uri-instructions: {uri-docs}/instructions.adoc
:uri-oci-keys: https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm
:uri-oci-ocids: https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm#five
:uri-oci-okepolicy: https://docs.cloud.oracle.com/iaas/Content/ContEng/Concepts/contengpolicyconfig.htm#PolicyPrerequisitesService
:uri-oci-provider: https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformproviderconfiguration.htm
:uri-oci-provider-precedence: https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformproviderconfiguration.htm#terraformproviderconfiguration_topic-Order_of_Precedence
:uri-provider-example: {uri-rel-file-base}/provider.tf.example
:uri-terraform: https://www.terraform.io
:uri-terraform-oci: https://www.terraform.io/docs/providers/oci/index.html
:uri-terraform-options: {uri-docs}/terraformoptions.adoc
:uri-terraform-precedence: https://www.terraform.io/docs/language/values/variables.html#variable-definition-precedence
:uri-variables: {uri-rel-file-base}/variables.tf
:uri-rms-zip: 

.Prerequisites
- {uri-oci-keys}[Required Keys and OCIDs]
- {uri-oci-okepolicy}[Required IAM policies]
- `git`, `ssh` client to run locally
- Terraform `>= 1.2.0` to run locally

== Provisioning from an OCI Resource Manager Stack
++++
<table>
  <tr>
    <th>Name</th>
    <th>Resources</th>
    <th>Deploy</th>
  </tr>
  <tr>
    <td>OKE Network Only</td>
    <td>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_vcn>core_vcn</a></li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_nat_gateway>core_nat_gateway</a></li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_internet_gateway>core_internet_gateway</a></li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_subnet>core_subnet</a> (all)</li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_instance>core_instance</a> (bastion)</li>
    </td>
    <td><a href=https://cloud.oracle.com/resourcemanager/stacks/create?zipUrl=https://objectstorage.ap-osaka-1.oraclecloud.com/p/LwHOyvlB0vrV7li0K03CDTGz5b12YLzqnBHVB4ud418o6ybBtHBVGzjehp5gK4Hw/n/hpc_limited_availability/b/temporary/o/oke-network-only.20230410.zip target="_blank">
        <img src="https://oci-resourcemanager-plugin.plugins.oci.oraclecloud.com/latest/deploy-to-oracle-cloud.svg" alt="Deploy to Oracle Cloud"/></a>
    </td>
  </tr>
  <tr>
    <td>OKE Cluster <i>(new network)</i></td>
    <td>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_vcn>core_vcn</a></li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_nat_gateway>core_nat_gateway</a></li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_internet_gateway>core_internet_gateway</a></li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_subnet>core_subnet</a> (configured)</li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_network_security_group>core_network_security_group</a></li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_network_security_group_security_rule>core_network_security_group_security_rule</a></li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_instance>core_instance</a> (bastion, operator)</li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/containerengine_cluster>containerengine_cluster</a></li>
    </td>
    <td><a href=https://cloud.oracle.com/resourcemanager/stacks/create?zipUrl=https://objectstorage.ap-osaka-1.oraclecloud.com/p/LwHOyvlB0vrV7li0K03CDTGz5b12YLzqnBHVB4ud418o6ybBtHBVGzjehp5gK4Hw/n/hpc_limited_availability/b/temporary/o/oke-cluster-with-network.20230410.zip&zipUrlVariables={"cluster_name":"oke-cluster-with-network"} target="_blank">
        <img src="https://oci-resourcemanager-plugin.plugins.oci.oraclecloud.com/latest/deploy-to-oracle-cloud.svg" alt="Deploy to Oracle Cloud"/></a>
    </td>
  </tr>
  <tr>
    <td>OKE Cluster <i>(existing network)</a></td>
    <td>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_network_security_group>core_network_security_group</a></li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_network_security_group_security_rule>core_network_security_group_security_rule</a></li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_instance>core_instance</a> (operator)</li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/containerengine_cluster>containerengine_cluster</a></li>
    </td>
    <td><a href=https://cloud.oracle.com/resourcemanager/stacks/create?zipUrl=https://objectstorage.ap-osaka-1.oraclecloud.com/p/LwHOyvlB0vrV7li0K03CDTGz5b12YLzqnBHVB4ud418o6ybBtHBVGzjehp5gK4Hw/n/hpc_limited_availability/b/temporary/o/oke-cluster-with-network.20230410.zip&zipUrlVariables={"cluster_name":"oke-cluster-existing-network","create_vcn":false,"create_nsgs":false,"create_bastion":false,"worker_subnet_create":"Never","control_plane_subnet_create":"Never","operator_subnet_create":"Never","bastion_subnet_create":"Never","pod_subnet_create":"Never","int_lb_subnet_create":"Never","pub_lb_subnet_create":"Never","fss_subnet_create":"Never"} target="_blank">
        <img src="https://oci-resourcemanager-plugin.plugins.oci.oraclecloud.com/latest/deploy-to-oracle-cloud.svg" alt="Deploy to Oracle Cloud"/></a>
    </td>
  </tr>
  <tr>
    <td>OKE-Managed Node Pool</td>
    <td>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/containerengine_node_pool>containerengine_node_pool</a></li>
    </td>
    <td><a href=https://cloud.oracle.com/resourcemanager/stacks/create?zipUrl=https://objectstorage.ap-osaka-1.oraclecloud.com/p/LwHOyvlB0vrV7li0K03CDTGz5b12YLzqnBHVB4ud418o6ybBtHBVGzjehp5gK4Hw/n/hpc_limited_availability/b/temporary/o/oke-workers.20230410.zip&zipUrlVariables={"worker_pool_mode":"Node%20Pool","worker_pool_name":"oke-node-pool"} target="_blank">
        <img src="https://oci-resourcemanager-plugin.plugins.oci.oraclecloud.com/latest/deploy-to-oracle-cloud.svg" alt="Deploy to Oracle Cloud"/></a>
    </td>
  </tr>
  <tr>
    <td>Self-Managed Instances</td>
    <td>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/identity_dynamic_group>identity_dynamic_group</a> (workers)</li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/identity_policy>identity_policy</a> (JoinCluster)</li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_instance>core_instance</a></li>
    </td>
    <td><a href=https://cloud.oracle.com/resourcemanager/stacks/create?zipUrl=https://objectstorage.ap-osaka-1.oraclecloud.com/p/LwHOyvlB0vrV7li0K03CDTGz5b12YLzqnBHVB4ud418o6ybBtHBVGzjehp5gK4Hw/n/hpc_limited_availability/b/temporary/o/oke-workers.20230410.zip&zipUrlVariables={"worker_pool_mode":"Instances","worker_pool_name":"oke-instances"} target="_blank">
        <img src="https://oci-resourcemanager-plugin.plugins.oci.oraclecloud.com/latest/deploy-to-oracle-cloud.svg" alt="Deploy to Oracle Cloud"/></a>
    </td>
  </tr>
  <tr>
    <td>Self-Managed Instance Pool</td>
    <td>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/identity_dynamic_group>identity_dynamic_group</a> (workers)</li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/identity_policy>identity_policy</a> (JoinCluster)</li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_instance_configuration>core_instance_configuration</a></li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_instance_pool>core_instance_pool</a></li>
    </td>
    <td><a href=https://cloud.oracle.com/resourcemanager/stacks/create?zipUrl=https://objectstorage.ap-osaka-1.oraclecloud.com/p/LwHOyvlB0vrV7li0K03CDTGz5b12YLzqnBHVB4ud418o6ybBtHBVGzjehp5gK4Hw/n/hpc_limited_availability/b/temporary/o/oke-workers.20230410.zip&zipUrlVariables={"worker_pool_mode":"Instance%20Pool","worker_pool_name":"oke-instance-pool"} target="_blank">
        <img src="https://oci-resourcemanager-plugin.plugins.oci.oraclecloud.com/latest/deploy-to-oracle-cloud.svg" alt="Deploy to Oracle Cloud"/></a>
    </td>
  </tr>
  <tr>
    <td>Self-Managed Cluster Network</td>
    <td>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/identity_dynamic_group>identity_dynamic_group</a> (workers)</li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/identity_policy>identity_policy</a> (JoinCluster)</li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_instance_configuration>core_instance_configuration</a></li>
      <li><a href=https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_cluster_network>core_cluster_network</a></li>
    </td>
    <td><a href=https://cloud.oracle.com/resourcemanager/stacks/create?zipUrl=https://objectstorage.ap-osaka-1.oraclecloud.com/p/LwHOyvlB0vrV7li0K03CDTGz5b12YLzqnBHVB4ud418o6ybBtHBVGzjehp5gK4Hw/n/hpc_limited_availability/b/temporary/o/oke-workers.20230410.zip&zipUrlVariables={"worker_pool_mode":"Cluster%20Network","worker_pool_name":"oke-cluster-network","worker_shape":"BM.GPU4.8"} target="_blank">
        <img src="https://oci-resourcemanager-plugin.plugins.oci.oraclecloud.com/latest/deploy-to-oracle-cloud.svg" alt="Deploy to Oracle Cloud"/></a>
    </td>
  </tr>
</table>
++++

== Configure OCI Terraform providers locally
Review {uri-oci-provider}[Configuring the OCI Terraform Provider] for additional detail.

.The module will need at least 2 instances of the `oci` provider in most cases for access to regional endpoints:
- 1 provider for the region where your OKE cluster and other resources will be created
- 1 provider for the home region. This is required for conducting identity operations. *Note that your home region may not necessarily be the same as your current region.*

.Create a provider.tf file in root with 2 providers. An {uri-provider-example}[example] is provided for convenience:
[source, shell]
----
cp provider.tf.example provider.tf
----

.Define the appropriate provider configuration for your {uri-oci-provider}[authentication method]. A full configuration may include the following:
----
provider "oci" {
  config_file_profile  = var.config_file_profile
  fingerprint          = var.api_fingerprint
  api_private_key_path = var.api_private_key_path
  private_key          = var.api_private_key
  private_key_password = var.api_private_key_password
  region               = var.region
  tenancy_ocid         = var.tenancy_ocid
  user_ocid            = var.current_user_ocid
}

provider "oci" {
  alias                = "home"
  config_file_profile  = var.config_file_profile
  fingerprint          = var.api_fingerprint
  api_private_key_path = var.api_private_key_path
  private_key          = var.api_private_key
  private_key_password = var.api_private_key_password
  region               = var.home_region
  tenancy_ocid         = var.tenancy_ocid
  user_ocid            = var.current_user_ocid
}
----

.The following may suffice in a Resource Manager Stack, with the home region determined using a Terraform datasource:
----
provider "oci" {
  alias        = "home"
  region       = one(data.oci_identity_region_subscriptions.home.region_subscriptions[*].region_name)
  tenancy_ocid = var.tenancy_ocid
  user_ocid    = var.current_user_ocid
}

provider "oci" {
  region                 = var.region
  tenancy_ocid           = var.tenancy_ocid
  user_ocid              = var.current_user_ocid
  retry_duration_seconds = 1800
}

data "oci_identity_region_subscriptions" "home" {
  tenancy_id = var.tenancy_ocid
  filter {
    name   = "is_home_region"
    values = [true]
  }
}
----

.Parameters may be defined using:
1. Environment variables (e.g. `TF_api_fingerprint`)
2. `terraform.tfvars/*.auto.tfvars` files

NOTE: Review {uri-terraform-precedence}[Terraform] and {uri-oci-provider-precedence}[OCI] variable definition order of precedence.

== Provision using the HashiCorp registry module
. {uri-oci-provider}[Configuring the OCI Terraform Provider]
. In your project root, create a `provider.tf` file and repeat the steps for creating providers as above.

. In your project root, create a `variables.tf` file and add variables for your project. You can copy the existing {uri-variables}[variables.tf] in the OKE module root.

. In your project root, create a `versions.tf` file and add the following:

+
----
terraform {
  required_providers {
    oci = {
      source                = "oracle/oci"
      configuration_aliases = [oci.home]
      version               = ">= 4.67.3"
    }
  }
  required_version = ">= 1.0.0"
}
----

.In your project root, create a main.tf file and add the following:
----
module "oke" {
  source  = "oracle-terraform-modules/oke/oci"
  version = "4.2.4"
  # insert required variables here
}
----

.Edit your OKE module definition and pass the required variables:
----
module "oke" {
  source                                =   "oracle-terraform-modules/oke/oci"
  version                               =   "5.0.0"

  compartment_id                        =   var.compartment_id
  tenancy_id                            =   var.tenancy_id

  ssh_private_key_path                  =   var.ssh_private_key_path
  ssh_public_key_path                   =   var.ssh_public_key_path

  label_prefix                          =   var.label_prefix
  home_region                           =   var.home_region
  region                                =   var.region

  vcn_name                              =   var.vcn_name

  create_bastion_host                   =   var.create_bastion_host
 
  create_operator                       =   var.create_operator

  # add additional parameters for availability_domains, oke etc as you need

  providers = {
    oci.home = oci.home
  }
}
----

.Run Terraform:
[source, shell]
----
terraform init
terraform plan
terraform apply
----

== Provision using this Git repo

.Clone the repo:
[source, shell]
----
git clone https://github.com/oracle-terraform-modules/terraform-oci-oke.git tfoke && cd tfoke
cp terraform.tfvars.example terraform.tfvars
----

Review the steps above to Configure OCI Terraform providers.

NOTE: Review {uri-terraform-precedence}[Terraform] and {uri-oci-provider-precedence}[OCI] variable definition order of precedence.

== Run Terraform
[source, shell]
----
terraform init     # With -upgrade for the latest module versions
terraform plan
terraform apply
----

== Related documentation
* {uri-instructions}[Detailed Instructions]
* {uri-terraform-options}[All Terraform configuration options] for {uri-repo}[this project]
