= Quickstart

:idprefix:
:idseparator: -
:sectlinks:


:uri-repo: https://github.com/oracle-terraform-modules/terraform-oci-oke
:uri-rel-file-base: link:{uri-repo}/blob/master
:uri-rel-tree-base: link:{uri-repo}/tree/master
:uri-docs: {uri-rel-file-base}/docs
:uri-instructions: {uri-docs}/instructions.adoc
:uri-oci-keys: https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm
:uri-oci-ocids: https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm#five
:uri-oci-okepolicy: https://docs.cloud.oracle.com/iaas/Content/ContEng/Concepts/contengpolicyconfig.htm#PolicyPrerequisitesService
:uri-terraform: https://www.terraform.io
:uri-terraform-oci: https://www.terraform.io/docs/providers/oci/index.html
:uri-terraform-options: {uri-docs}/terraformoptions.adoc
:uri-topology: {uri-docs}/topology.adoc
:uri-variables: {uri-rel-file-base}/variables.tf

. link:#assumptions[Assumptions]
. link:#pre-requisites[Pre-requisites]
. link:#instructions[Instructions]
. link:#related-documentation[Related documentation]

=== Assumptions

1. You have setup the {uri-oci-keys}[required keys]
2. You know the {uri-oci-ocids}[required OCIDs]
3. You have set the {uri-oci-okepolicy}[necessary OKE policy]

=== Pre-requisites

1. git is installed
2. ssh client is installed
3. Terraform 0.12.16+ is installed

=== Provisioning using this git repo

. Clone the repo:

+
[source,bash]
----
git clone https://github.com/oracle-terraform-modules/terraform-oci-oke.git tfoke

cd tfoke
cp terraform.tfvars.example terraform.tfvars
----

. Create a provider.tf file and add the following:

+
----
provider "oci" {
  tenancy_ocid         = var.tenancy_id
  user_ocid            = var.user_id
  fingerprint          = var.api_fingerprint
  private_key_path     = var.api_private_key_path
  region               = var.region
  disable_auto_retries = var.disable_auto_retries
}
----

. Set mandatory parameters:

* api_fingerprint
* api_private_key_path
* compartment_id
* compartment_name
* tenancy_id
* user_id

. Override other parameters:

* region

. Optional parameters to override:
* bastion_enabled
* cluster_name
* ssh_private_key_path (Required if bastion is enabled)
* ssh_public_key_path (Required if bastion is enabled)
* vcn_dns_label
* vcn_name
* worker_mode

. Run Terraform:

+
[source,bash]
----
terraform init
terraform plan
terraform apply
----

=== Provisioning using the Hashicorp registry module

. In your project root, create a provider.tf file and add the following:

+
----
provider "oci" {
  tenancy_ocid         = var.tenancy_id
  user_ocid            = var.user_id
  fingerprint          = var.api_fingerprint
  private_key_path     = var.api_private_key_path
  region               = var.region
  disable_auto_retries = var.disable_auto_retries
}
----

. In your project root, create a variables.tf file and add variables for your project. You can copy the existing {uri-variables}[variables.tf] in the oke module root.

. In your project root, create a main.tf file and add the following:

+
----
module "oke" {
  source  = "oracle-terraform-modules/oke/oci"
  version = "2.1.5"
  # insert the 23 required variables here
}
----

. Edit your oke module definition and pass the required variables:

+
----
module "oke" {
  source                                =   "oracle-terraform-modules/oke/oci"
  version                               =   "2.1.5"

  compartment_id                        =   var.compartment_id
  tenancy_id                            =   var.tenancy_id
  user_id                               =   var.user_id

  ssh_private_key_path                  =   var.ssh_private_key_path
  ssh_public_key_path                   =   var.ssh_public_key_path

  label_prefix                          =   var.label_prefix
  region                                =   var.region

  vcn_dns_label                         =   var.vcn_dns_label
  vcn_name                              =   var.vcn_name

  bastion_shape                         =   var.bastion_shape
  bastion_timezone                      =   var.bastion_timezone

  admin_shape                           =   var.admin_shape
  admin_timezone                        =   var.admin_timezone

  # add additional parameters for availability_domains, oke etc as you need

}
----

. Run Terraform:

+
[source,bash]
----
terraform init
terraform plan
terraform apply
----

=== Related documentation:

* {uri-instructions}[Detailed Instructions]

* {uri-terraform-options}[All Terraform configuration options] for {uri-repo}[this project]
