= OKE Terraform Module
:idprefix:
:idseparator: -
:sectlinks:
:sectnums:
:toc: auto

// Github
:uri-repo: https://github.com/oracle-terraform-modules/terraform-oci-oke
:uri-rel-file-base: link:{uri-repo}/blob/main
:uri-rel-tree-base: link:{uri-repo}/tree/main
:uri-docs: {uri-rel-file-base}/docs

// Local
:uri-docs-bastion: link:bastion.adoc
:uri-docs-cluster: link:cluster.adoc
:uri-docs-extensions: link:extensions.adoc
:uri-docs-identity: link:identity.adoc
:uri-docs-networking: link:networking.adoc
:uri-docs-operator: link:operator.adoc
:uri-docs-provider: link:provider.adoc
:uri-docs-ssh: link:ssh.adoc
:uri-docs-utilities: link:utilities.adoc
:uri-docs-workers: link:workers.adoc

:uri-oci-content: https://docs.cloud.oracle.com/iaas/Content

== Configuration

=== {uri-docs-provider}[Provider]
=== {uri-docs-identity}[Identity]
=== {uri-docs-ssh}[SSH]
=== {uri-docs-bastion}[Bastion]
=== {uri-docs-operator}[Operator]
=== {uri-docs-cluster}[Cluster]
=== {uri-docs-workers}[Workers]
=== {uri-docs-utilities}[Utilities]
=== {uri-docs-extensions}[Extensions]

== Usage

=== Create

.Initialize a working directory containing Terraform configuration files, and optionally upgrade module dependencies:
----
terraform init -upgrade
----

.Run the plan and apply commands to create OKE cluster and other components:
----
terraform plan
terraform apply
----

You can create a Kubernetes cluster with the latest version of Kubernetes available in OKE using this terraform script. By default the kubernetes_version parameter in terraform.tfvars.example is set as "LATEST". Refer to {uri-terraform-options}#oke[Terraform Options] for other available parameters for OKE.

Use the parameter *cluster_name* to change the name of the cluster as per your needs.

=== Connect

NOTE: TODO Add content

kubectl installed on the operator host by default and the kubeconfig file is set in the default location (~/.kube/config) so you don't need to set the KUBECONFIG environment variable every time you log in to the operator host. 

****
N.B. In order for kubeconfig to be created on the operator host, you need to link:#enabling-instance_principal-on-the-operator-host[enable instance_principal on the operator host].
****

An alias "*k*" will be created for kubectl on the operator host. 

If you would like to use kubectl locally, {uri-install-kubectl}[install kubectl]. Then, set the KUBECONFIG to the config file path.

----
export KUBECONFIG=path/to/kubeconfig
----

.To be able to get the kubeconfig file, you will need to get the credentials with terraform and store in the preferred storage format (e.g: file, vault, bucket...):
[source,hcl]
----
# OKE cluster creation.
module "oke_my_cluster" {
#...
}

# Obtain cluster Kubeconfig.
data "oci_containerengine_cluster_kube_config" "kube_config" {
  cluster_id = module.oke_my_cluster.cluster_id
}

# Store kubeconfig in vault.
resource "vault_generic_secret" "kube_config" {
  path = "my/cluster/path/kubeconfig"
  data_json = jsonencode({
    "data" : data.oci_containerengine_cluster_kube_config.kube_config.content
  })
}

# Store kubeconfig in file.
resource "local_file" "kube_config" {
  content         = data.oci_containerengine_cluster_kube_config.kube_config.content
  filename        = "/tmp/kubeconfig"
  file_permission = "0600"
}
----

****
*Ensure you install the same kubectl version as the OKE Kubernetes version for compatibility.*
****

=== Update

NOTE: TODO Add content

=== Destroy

NOTE: TODO Add content

Run the below command to destroy the infrastructure created by Terraform:

----
terraform destroy
----

****
*Only infrastructure created by Terraform will be destroyed.*
****

== Examples

=== Standard

NOTE: TODO Add content

=== Network only

NOTE: TODO Add content

=== Cluster with existing network

NOTE: TODO Add content

=== Custom cloud-init

NOTE: TODO Add content

=== Cluster autoscaler

NOTE: TODO Add content
